_format_version: "2.1"
_transform: true

services:
- host: 103.189.234.51
  name: keycloak_service
  port: 8080
  protocol: http
  plugins:
  - name: oidc
    config:
      discovery: http://103.250.11.93:8080/realms/allo-sandbox/.well-known/openid-configuration
      client_id: allo-service
      client_secret: 6dIMJfI8HYWAL5bOCNnB3wJm6WW00SZ7
  routes:
  - name: keycloak_route
    paths:
    - /keycloak
    strip_path: true
