# _format_version: "2.1"
# _transform: true

# services:
#   - host: localhost
#     name: keycloak
#     port: 8080
#     protocol: http
#     plugins:
#       - name: oidc
#         config:
#           discovery: http://localhost:8080/realms/allo-sandbox/.well-known/openid-configuration
#           client_id: allo-service
#           client_secret: kQ3i9a0UNvn3i7UBTOXZ3Ltan20Cn8pi
#     routes:
#       - name: keycloak_route
#         paths:
#           - /keycloak
#         strip_path: true
